In [1]:
# import pytorch libraries
%matplotlib inline
import torch 
import torch.autograd as autograd 
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
# Create random tensor
N = 5
x = torch.randn(N, 10).type(torch.FloatTensor)

In [20]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
a.shape

(2, 3)

In [22]:
at = np.transpose(a)

In [23]:
at

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
at.shape

(3, 2)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
ai = np.invert(a)

In [28]:
ai

array([[-2, -3, -4],
       [-5, -6, -7]])

In [29]:
ai * a

array([[ -2,  -6, -12],
       [-20, -30, -42]])

In [60]:
b=np.array([[1,2],[3,4]])

In [61]:
b

array([[1, 2],
       [3, 4]])

In [62]:
bi = np.linalg.inv(b)

In [63]:
bi

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
i = np.dot(bi,b)

In [65]:
i

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [42]:
i = np.identity(2)

In [43]:
i

array([[1., 0.],
       [0., 1.]])

In [44]:
bb = np.dot(b,i)

In [45]:
bb

array([[1., 2.],
       [3., 4.]])

array([[1, 2],
       [3, 4]])

In [49]:
q = np.dot(bi,i)

In [50]:
q

array([[-2., -3.],
       [-4., -5.]])

In [51]:
i

array([[1., 0.],
       [0., 1.]])